version: "2.0"
services: 
  mariadb:
      container_name: aghdrive-mariadb
      hostname: aghdrive-mariadb
      restart: always
      build:
        context: ./
        dockerfile: mariadb.dockerfile # build Docker image
      environment:
        MYSQL_ROOT_PASSWORD: "root123"
        MYSQL_DATABASE: "aghdrive"
        MYSQL_USER: "aghdrive"
        MYSQL_PASSWORD: "aghdrive123"
        TZ: "Europe/Warsaw" # do sprawdzenie
      volumes:
        - ../db:/var/lib/mysql
        - ../log/mariadb:/var/lib/mysql/logs
      expose:
        - 3306 # expose port 3306 to other containers (and not to the host)
      ports:
        - 9100:3306

  phpapache:
    container_name: aghdrvie-php-apache
    hostname: aghdrvie-php-apache
    restart: always
    build:
        context: ./ 
        dockerfile: phpapache.dockerfile
    volumes:
        - ../sites:/sites
        - ../etc/apache2:/etc/apache2
        - ../certs:/etc/ssl/certs
        - ../data:/mnt/data
    expose:
        - 80 8080 443
    ports:
        - 9180:80
        - 9181:443

# docker-compose -f docker-compose.yml -p "agh-drive" up, https://stackoverflow.com/questions/53401672/stack-name-with-docker-compose
# docker-compose up -d
# docker-compose -f docker-compose.yml -p "agh-drive" build -d
# Zmiana strefy czasowej mariadb https://mariadb.com/kb/en/time-zones/

# Jesli przy imporcie db komendą:
# 
# są błędy: ERROR 1227 (42000) at line 529: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
# trzeba zamienić DEFINER=`aghdrive`@`localhost` na DEFINER=`aghdrive`@`%`